# -*- coding: utf-8 -*-
"""Wuzzuf jobs Scraping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jf-l77agaQo2eIbwBiI7Rc3N5RzZHEvs
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd

titles=[]
occupations=[]
companies_names=[]
companies_locs=[]
specs_all=[]
links=[]

pages=[]

for i in range(3):
  pages.append('https://wuzzuf.net/search/jobs/?a=hpb&q=Machine%20learning&start='+str(i))
for i in range(38):
  pages.append('https://wuzzuf.net/search/jobs/?a=hpb%7Cspbg&q=data%20science&start='+str(i))
for i in range(42):
  pages.append('https://wuzzuf.net/search/jobs/?a=hpb%7Cspbg&q=data%20analysis&start='+str(i))
for i in range(5):
  pages.append('https://wuzzuf.net/search/jobs/?a=hpb%7Cspbg&q=business%20intelligence&start='+str(i))

for page in pages:
  response=requests.get(page)
  soup=BeautifulSoup(response.content,'lxml')
  #title-----------------------------------------
  title=soup.find_all('h2',{'class':"css-m604qf"})
  #job_link---------------------------------------------
  job_link=[link.a['href'] for link in title]
  job_link=['https://wuzzuf.net'+link for link in job_link]
  job_link= [ link.replace(' ','%20') for link in job_link]
  #----------------------------------------------------
  title=[t.a.text for t in title]
  #occupation--------------------------------------------
  occupation=soup.find_all('div',{'class':"css-1lh32fc"})
  occupation=[oc.text for oc in occupation]
  occupation[0]= occupation[0][occupation[0].rfind("}")+1:]
  #company_name--------------------------------------------
  company_name=soup.find_all('div',{'class':"css-d7j1kk"})
  company_name=[com.a.text.rstrip('-').rstrip() for com in company_name]
  #company_loc-----------------------------------------------------
  company_loc=soup.find_all('span',{'class':"css-5wys0k"})
  company_loc=[loc.text for loc in company_loc]
  #specs-----------------------------------------
  specs=soup.find_all('div',{'class':"css-y4udm8"})
  specs=soup.find_all('div',{'class':"css-y4udm8"})
  specs=[sp.text for sp in specs]
  part1= specs[0][specs[0].rfind('}')+1:]
  specs[0]= specs[0] [:specs[0].rfind('}')]
  part2= specs[0][specs[0].rfind('}')+1:]
  specs[0]=part2[:part2.find('css-5x9pm1') ] +part1
  #ADD ALL TO THE MAIN LISTS
  titles=titles+title
  occupations=occupations+occupation
  companies_names=companies_names+company_name
  companies_locs=companies_locs+company_loc
  specs_all=specs_all+specs
  links=links+job_link

scrapped_jobs={}
scrapped_jobs['Job Title']=titles
scrapped_jobs['Job Type']=occupations
scrapped_jobs['Company Name']= companies_names
scrapped_jobs['Company Location']= companies_locs
scrapped_jobs['Specifications']=specs_all
scrapped_jobs['Job Link']=links

jobs_dataframe= pd.DataFrame(scrapped_jobs)

jobs_dataframe

jobs_dataframe.to_csv('wuzzuf_jobs.csv',index=False)

